services:

  discovery:
    image: eurekaserver:latest
    build:
      context: ./discovery
    container_name: discovery
    ports:
      - "8761:8761"
    networks:
      - sitnetwork

  db:
    image: postgres:15
    container_name: customer-db
    environment:
      POSTGRES_DB: customer_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - customer_db_data:/var/lib/postgresql/data
    networks:
      - sitnetwork

  customer-service:
    build:
      context: ./customer-service
    container_name: customer-service
    depends_on:
      - db
      - discovery
    ports:
      - "8081:8081"
    env_file:
      - ./.env
    networks:
      - sitnetwork

networks:
  sitnetwork:
    driver: bridge

volumes:
  customer_db_data:
