# Define os serviços (contêineres)
services:

  # Serviço do Banco de Dados PostgreSQL
  db:
    image: postgres:15
    container_name: customer-db
    environment:
      POSTGRES_DB: customer_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      # Expõe a porta 5433 no seu computador, mapeando para a 5432 do contêiner
      - "5433:5432"
    volumes:
      - customer_db_data:/var/lib/postgresql/data
    networks:
      - sitnetwork

  # Serviço da sua aplicação Customer
  customer-service:
    build:
      context: .
    container_name: customer-service # Adicionado para consistência
    depends_on:
      - discovery
    ports:
      - "8081:8081"
    env_file:
      - .env
    networks:
      - sitnetwork
    environment:
      - EUREKA_HOST=discovery
      - EUREKA_PORT=8761
      - DB_HOST=db
      - DB_NAME=customer_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres

# Define a rede que permite a comunicação entre os contêineres
networks:
  sitnetwork:
    external: true

# Define o volume para persistir os dados do banco de dados
volumes:
  customer_db_data: