services:
  config:
    build:
      context: ./config-server
    container_name: config
    ports:
      - "8888:8888"
    networks:
      - sit-network
    volumes:
      - ./config-server/config:/app/config-repo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: on-failure

  eureka:
    build:
      context: ./eureka
    container_name: eureka
    ports:
      - "8761:8761"
    networks:
      - sit-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: on-failure
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - sit-network
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    # ADICIONADO: Healthcheck para o Postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # customer-service:
  #   build:
  #     context: ./customer/customer-service
  #   container_name: customer-service # Nome padronizado
  #   depends_on:
  #     # CORRIGIDO: Sintaxe longa com condições
  #     postgres:
  #       condition: service_healthy
  #     eureka:
  #       condition: service_healthy
  #     config:
  #       condition: service_healthy
  #   ports:
  #     - "8081:8081"
  #   env_file:
  #     - .env 
  #   environment:
  #    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
  #     - SPRING_CONFIG_IMPORT=configserver:http://config:8888
  #   networks:
  #     - sit-network

  # financial-service:
  #   build:
  #     context: ./financial/financial-service
  #   container_name: financial-service # Nome padronizado
  #   depends_on:
  #     # CORRIGIDO: Sintaxe longa com condições
  #     postgres:
  #       condition: service_healthy
  #     eureka:
  #       condition: service_healthy
  #     config:
  #       condition: service_healthy
  #   ports:
  #     - "8082:8082"
  #   env_file:
  #     - .env 
  #   environment:
  #     - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
  #     - SPRING_CONFIG_IMPORT=configserver:http://config:8888
  #   networks:
  #     - sit-network
      
  user-service:
    build:
      context: ./users
    container_name: user-service 
    depends_on:
      postgres:
        condition: service_healthy
      config:
        condition: service_healthy
      eureka:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file:
      - .env 
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    networks:
      - sit-network

  # human-resources-service:
  #   build:
  #     context: ./human-resources/human-resources-service
  #   container_name: human-resources-service # Nome padronizado
  #   depends_on:
  #     # CORRIGIDO: Sintaxe longa com condições
  #     postgres:
  #       condition: service_healthy
  #     eureka:
  #       condition: service_healthy
  #     config:
  #       condition: service_healthy
  #   ports:
  #     - "8083:8083"
  #   env_file:
  #     - .env 
  #   environment:
  #     - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
  #     - SPRING_CONFIG_IMPORT=configserver:http://config:8888
  #   networks:
  #     - sit-network

  # operational-service:
  #   build:
  #     context: ./operational/operational-service 
  #   container_name: operational-service # Nome padronizado
  #   depends_on:
  #     # CORRIGIDO: Sintaxe longa com condições
  #     postgres:
  #       condition: service_healthy
  #     eureka:
  #       condition: service_healthy
  #     config:
  #       condition: service_healthy
  #   ports:
  #     - "8084:8084"
  #   env_file:
  #     - .env  
  #   environment:
  #     - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
  #     - SPRING_CONFIG_IMPORT=configserver:http://config:8888
  #   networks:
  #     - sit-network

networks:
  sit-network:
    driver: bridge

volumes:
  pg_data:
