services:
  discovery:
    build:
      context: ./eureka
    container_name: eureka
    ports:
      - "8761:8761"
    networks:
      - sit-network

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: customer_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5433"
    networks:
      - sit-network
    volumes:
      - pg_data:/var/lib/postgresql/data

  customer-service:
    build:
      context: ./customer/customer-service
    container_name: customer
    depends_on:
      - discovery
      - postgres
    ports:
      - "8081:8081"
    environment:
      - EUREKA_HOST=discovery
      - EUREKA_PORT=8761
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=customer_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    networks:
      - sit-network

networks:
  sit-network:
    driver: bridge

volumes:
  pg_data:
