services:
  discovery:
    build:
      context: ./eureka
    container_name: eureka
    ports:
      - "8761:8761"
    networks:
      - sit-network

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: sit
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - sit-network
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  customer-service:
    build:
      context: ./customer/customer-service
    container_name: customer
    depends_on:
      - discovery
      - postgres
    ports:
      - "8081:8081"
    environment:
      - EUREKA_HOST=discovery
      - EUREKA_PORT=8761
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=sitcustomers
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    networks:
      - sit-network
  financial-service:
    build:
      context: ./financial/financial-service
    container_name: financial
    depends_on:
      - discovery
      - postgres
    ports:
      - "8082:8082"
    environment:
      - EUREKA_HOST=discovery
      - EUREKA_PORT=8761
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=sitfinancial
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    networks:
      - sit-network
      
  user-service:
    build:
      context: ./users
    container_name: users
    depends_on:
      - discovery
      - postgres
    ports:
      - "8080:8080"
    environment:
      - EUREKA_HOST=discovery
      - EUREKA_PORT=8761
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=situsers
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    networks:
      - sit-network

networks:
  sit-network:
    driver: bridge

volumes:
  pg_data:
