services:
  config:
    build:
      context: ./config-server
    container_name: config
    ports:
      - "8888:8888"
    networks:
      - sit-network
    depends_on:
    - eureka
    volumes:
    - ./config-server/config:/app/config-repo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: on-failure
  eureka:
    build:
      context: ./eureka
    container_name: eureka
    ports:
      - "8761:8761"
    networks:
      - sit-network

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - sit-network
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  customer-service:
    build:
      context: ./customer/customer-service
    container_name: customer
    depends_on:
      - postgres
      - eureka
      - config
    ports:
      - "8081:8081"
    environment:
      - EUREKA_HOST=eureka
      - EUREKA_PORT=8761
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=sitcustomers
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    networks:
      - sit-network
  financial-service:
    build:
      context: ./financial/financial-service
    container_name: financial
    depends_on:
      - postgres
      - eureka
      - config
    ports:
      - "8082:8082"
    environment:
      - EUREKA_HOST=eureka
      - EUREKA_PORT=8761
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=sitfinancial
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    networks:
      - sit-network
      
  user-service:
    build:
      context: ./users
    container_name: users
    depends_on:
      - postgres
      - eureka
      - config
    ports:
      - "8080:8080"
    environment:
      - EUREKA_HOST=eureka
      - EUREKA_PORT=8761
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=situsers
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    networks:
      - sit-network


  human-resources-service:
    build:
      context: ./human-resources/human-resources-service
    container_name: human-resources
    depends_on:
      - postgres
      - eureka
      - config
    ports:
      - "8083:8083"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=sithumanresources
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - HR_ENCRYPTION_KEY=my-super-secret-and-long-encryption-key-12345
    networks:
      - sit-network

  operational-service:
    build:
      context: ./operational/operational-service 
    container_name: operational
    depends_on:
      - eureka
      - postgres
      - config
    ports:
      - "8084:8084" 
    environment:
      - EUREKA_HOST=eureka
      - EUREKA_PORT=8761
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=sitoperational
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    networks:
      - sit-network
networks:
  sit-network:
    driver: bridge

volumes:
  pg_data:
