version: '3.8'

services:
  # API Gateway
  api-gateway:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - operational-service
      - client-service
      - financial-service
      - hr-service
    networks:
      - logistics-network

  # Service Discovery
  eureka-server:
    image: logistics/eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - logistics-network

  # Operational Service
  operational-service:
    build: ./operational-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://operational-db:5432/operational_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - EUREKA_URI=http://eureka-server:8761/eureka
      - CLIENT_SERVICE_URL=http://client-service/api/clients
      - KAFKA_SERVERS=kafka:9092
    depends_on:
      - operational-db
      - kafka
      - eureka-server
    networks:
      - logistics-network

  # Operational Database
  operational-db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=operational_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - operational-data:/var/lib/postgresql/data
    networks:
      - logistics-network

  # Operational Frontend
  operational-frontend:
    build: ./operational-frontend
    ports:
      - "3002:80"
    depends_on:
      - api-gateway
    networks:
      - logistics-network

  # Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - logistics-network

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - logistics-network

networks:
  logistics-network:
    driver: bridge

volumes:
  operational-data: