  server:
    port: 8888

  spring:
    profiles:
      active: native
    cloud:
      config:
        server:
          native:
            search-locations: file:/app/config-repo
        label: main
  eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://eureka:8761/eureka/