server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:/app/config-repo
eureka:
  client:
    enabled: false
management:
  endpoints:
    web:
      exposure:
        include: "*" # ou health,info