spring:
  application:
    name: user-service

  config:
    import: optional:configserver:http://config-server:8888

  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:situsers}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:123}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: always
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    generate-ddl: true

server:
  port: 8082

jwt:
  public:
    key: | 
      -----BEGIN PUBLIC KEY-----
      MIGeMA0GCSqGSIb3DQEBAQUAA4GMADCBiAKBgGh2dD3EQ9H7jIdzIqHO8GgXQw32
      QI7loxKzNj+3mCqgny1nDfATgAz6ERcr+jHAat+kDPp0RZkqHMEeFJiMtYQhR7mc
      1t+H0vMv3bkHrJSE96a++2vQjn97mXsCd39X7yUp2LHiFXVHEXL0l6Ls1/CDBKKV
      EA4GhLB94uggi3UfAgMBAAE=
      -----END PUBLIC KEY-----
  private:
    key: | 
      -----BEGIN RSA PRIVATE KEY-----
      MIICXAIBAAKBgGh2dD3EQ9H7jIdzIqHO8GgXQw32QI7loxKzNj+3mCqgny1nDfAT
      gAz6ERcr+jHAat+kDPp0RZkqHMEeFJiMtYQhR7mc1t+H0vMv3bkHrJSE96a++2vQ
      jn97mXsCd39X7yUp2LHiFXVHEXL0l6Ls1/CDBKKVEA4GhLB94uggi3UfAgMBAAEC
      gYBb9huy3HrP+mDmRQdx5tlg6UmQmv6OTb5Xkgjp4thEfo5iy9xLQv9xbRtqiL6C
      2d+77ZG3UnCKu7YAlFiRSx3nhqezI/XvQj5HoPv2RmIUa7CfXaCibQrgwSmjIFep
      I+8ad+3qkGxHerSKovHSlkcIFzTlUF9Bwp8TU8mXzawkoQJBAL4m38ZDjVLc4sWK
      w6OzmTEFUy9Bdh3Gtp9FUms08Ca+McyjDjiLuLEI6A1gaKw6h84pC84MSdkemqb5
      NFwQFCcCQQCMoynjB8ZIiANfiyDCGhIi24zM3Lh3ZV5L7nlti/rHQ+VNbdtCR9Ou
      iRdenCY9e+E/GVEpMtguSFIemKUsIFpJAkAx4y0ObSakuMLeJNvTFQl57PW4DiqZ
      AUtkWeGXstnWsEuMbrMKbs3T1IxdBhAwL2L12Zr5QgwV5IuahwMPrEA9AkEAiny1
      Z4mlWJEO+UuQc3Kmv0qBCM6km3XneFAZpKT9yrDyIN/30/nU2f7HU3PiOBM/yBnP
      EQmvVUwECXr40038eQJBAKKVj4sJSj2WdQ94wwTgEuK3Ns9XB1fkgH+s4unLqnUd
      yTOuF9MloFxJCU5Xmv/ifStJFrOvXDNU7gB7rcPOgJc=
      -----END RSA PRIVATE KEY-----


eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:eureka}:${EUREKA_PORT:8761}/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    com.sittransportadora.utilitary.StringToRSAKeyConverter: debug