# application-prod.yml
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:hr_service}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

logging:
  level:
    com.logistics.hr: INFO
    org.springframework: ERROR
  file:
    name: /var/log/hr-service/hr-service.log