# application-dev.yml
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hr_service
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    com.logistics.hr: DEBUG
    org.hibernate.SQL: DEBUG